version: '3.8'

services:
  shift-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV=${APP_ENV}
    ports:
      - "8087:8080"
    depends_on:
      mysql:
        condition: service_healthy
      mongo:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - APP_PORT=${APP_PORT}
      - DB_MYSQL_HOST=mysql
      - DB_MYSQL_PORT=${DB_MYSQL_PORT}
      - DB_MYSQL_USERNAME=${DB_MYSQL_USERNAME}
      - DB_MYSQL_PASSWORD=${DB_MYSQL_PASSWORD}
      - DB_MYSQL_NAME=${DB_MYSQL_NAME}
      - DB_MONGO_HOST=mongo
      - DB_MONGO_PORT=${DB_MONGO_PORT}
      - DB_MONGO_NAME=${DB_MONGO_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - ENV=${APP_ENV}
      - LOG_LEVEL=${LOG_LEVEL}
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - GOOGLE_ACCESS_TOKEN_URL=${GOOGLE_ACCESS_TOKEN_URL}
    networks:
      - shift-net

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Passw0rd123
      MYSQL_DATABASE: shift_local
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - shift-net
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${DB_MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - shift-net

  redis:
    image: redis:latest
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD} --databases 5 --dbfilename redis.db --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - shift-net

volumes:
  mysql_data:
  mongo_data:
  redis_data:

networks:
  shift-net:
